openapi: 3.0.2
info:
  title: API de Clientes
  version: "1.0"
tags:
  - name: Clientes
    description: Operações relacionadas aos clientes
paths:
  /clientes:
    post:
      tags:
        - Clientes
      summary: Cria um novo cliente
      security:
        - ClientCredentials: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        "201":
          description: Cliente criado com sucesso
        "400":
          description: Requisição inválida

    get:
      tags:
        - Clientes
      summary: Obtém uma lista de clientes
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cliente"

  /clientes/{id}:
    get:
      tags:
        - Clientes
      summary: Obtém um cliente pelo ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "404":
          description: Cliente não encontrado

    put:
      tags:
        - Clientes
      summary: Atualiza um cliente pelo ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
      responses:
        "200":
          description: Cliente atualizado com sucesso
        "404":
          description: Cliente não encontrado
        "400":
          description: Requisição inválida

    delete:
      tags:
        - Clientes
      summary: Exclui um cliente pelo ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Cliente excluído com sucesso
        "404":
          description: Cliente não encontrado

components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
          format: email

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://keycloak.example.com/realms/your-realm/protocol/openid-connect/token
          scopes: {}

security:
  - BearerAuth: []
